import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-neutral-300 font-sans selection:bg-white selection:text-black pt-24 pb-32">
      <div className="max-w-3xl mx-auto px-6 sm:px-12">
        <Link href="/" className="inline-flex items-center text-sm font-medium text-neutral-500 hover:text-white transition-colors mb-12">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-bold tracking-tighter text-white mb-8">Terms of Service</h1>
        <p className="text-sm text-neutral-500 mb-12">Last Updated: June 30, 2026</p>

        <div className="space-y-10 text-base leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing or using Indecode ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
            <p className="mb-4">
              Indecode is an AI-powered software engineering platform that reads your codebase, generates implementation plans, writes code, and opens Pull Requests. The Service is provided "as is" and is subject to continuous development and updates.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. GitHub Integration and Permissions</h2>
            <p className="mb-4">
              To function, Indecode requires access to your GitHub repositories. By granting access, you authorize us to read your code, create branches, and open pull requests on your behalf. You are responsible for reviewing all code generated by Indecode before merging it into your production environments.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Code Ownership and Liability</h2>
            <p className="mb-4">
              You retain full ownership of all code in your repositories. Indecode claims no ownership over the code it generates for you. 
            </p>
            <p className="mb-4 font-medium text-white">
              Disclaimer of Warranties: Indecode makes no guarantees regarding the accuracy, security, or reliability of the AI-generated code. You agree that Indecode shall not be liable for any damages, security breaches, or data loss resulting from the deployment or use of the generated code.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Acceptable Use</h2>
            <p className="mb-4">
              You agree not to use Indecode for any unlawful purposes, to generate malicious code, or to attempt to breach the security of the platform. We reserve the right to terminate accounts that violate these guidelines without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Changes to Terms</h2>
            <p className="mb-4">
              We may modify these Terms at any time. We will notify you of any material changes by posting the new Terms on this site. Your continued use of the Service after changes constitute acceptance of the modified Terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
